
spring.config.import=optional:file:.env[.properties]

# Database connection using variables
spring.application.name=${DB_NAME}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# High-performance settings for AWS RDS
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5

# Retire connections at 25 mins to beat the AWS Network idle-kill (usually 30m-60m)
spring.datasource.hikari.max-lifetime=1500000

# Keep the connection 'warm' so the firewall doesn't kill it
spring.datasource.hikari.keepalive-time=30000

# DO NOT use connection-test-query if you can avoid it; it's slow.
# Hikari will use the faster JDBC4 isValid() check automatically.
# spring.datasource.hikari.connection-test-query=SELECT 1 (Comment this out)

spring.datasource.hikari.validation-timeout=2000
spring.datasource.hikari.connection-timeout=10000
spring.security.user.name=${APP_USER}
spring.security.user.password=${APP_PASSWORD}

spring.jpa.open-in-view=false

metalbroker.feed.base-url=https://goldbroker.com/api
# Schedulers Configuration (MANDATORY)
metalbroker.feed.metals=gold,silver,platinum,palladium
metalbroker.feed.currency=INR
metalbroker.feed.weight-unit=g
metalbroker.feed.intraday-retention-days=7

# Interval timings in milliseconds
metalbroker.feed.latest-interval-ms=10000
metalbroker.feed.intraday-interval-ms=300000


# Recommended MySQL driver hint (optional)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# Flyway (migrations)
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1
spring.jpa.hibernate.ddl-auto=none


#caching check

logging.level.org.springframework.cache=TRACE
logging.level.org.springframework.cache.interceptor=TRACE
logging.level.io.nats=DEBUG
logging.level.io.nats.client=DEBUG

# (Optional) Helpful logging during Phase 1
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=warn
logging.level.org.hibernate.type.descriptor.sql=warn


# JWT Secret (Must be 32+ characters)
jwt.secret=${JWT_SECRET}


# ===============================
# Cache (REDIS)
# ===============================
spring.cache.type=redis

# ===============================
# Redis connection
# ===============================
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2s

# ===============================
# Redis client (Lettuce pool)
# ===============================
spring.data.redis.lettuce.pool.max-active=16
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=2
spring.data.redis.lettuce.pool.max-wait=2s

# ===============================
# Disable null caching (safety)
# ===============================
spring.cache.redis.cache-null-values=false